# Generated by Django 4.2 on 2024-01-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_businessprocess_dgd_code_column_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocess",
            name="dgd_name_column",
            field=models.IntegerField(
                choices=[
                    (0, "A column"),
                    (1, "B column"),
                    (2, "C column"),
                    (3, "D column"),
                    (4, "E column"),
                    (5, "F column"),
                    (6, "G column"),
                    (7, "H column"),
                    (8, "I column"),
                    (9, "J column"),
                    (10, "K column"),
                    (11, "L column"),
                    (12, "M column"),
                    (13, "N column"),
                    (14, "O column"),
                    (15, "P column"),
                    (16, "Q column"),
                    (17, "R column"),
                    (18, "S column"),
                    (19, "T column"),
                    (20, "U column"),
                    (21, "V column"),
                    (22, "W column"),
                    (23, "X column"),
                    (24, "Y column"),
                    (25, "Z column"),
                ],
                default=1,
                verbose_name="DGD name column",
            ),
        ),
        migrations.AlterField(
            model_name="businessprocess",
            name="ugd_code_column",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "A column"),
                    (1, "B column"),
                    (2, "C column"),
                    (3, "D column"),
                    (4, "E column"),
                    (5, "F column"),
                    (6, "G column"),
                    (7, "H column"),
                    (8, "I column"),
                    (9, "J column"),
                    (10, "K column"),
                    (11, "L column"),
                    (12, "M column"),
                    (13, "N column"),
                    (14, "O column"),
                    (15, "P column"),
                    (16, "Q column"),
                    (17, "R column"),
                    (18, "S column"),
                    (19, "T column"),
                    (20, "U column"),
                    (21, "V column"),
                    (22, "W column"),
                    (23, "X column"),
                    (24, "Y column"),
                    (25, "Z column"),
                ],
                default=2,
                null=True,
                verbose_name="UGD code column",
            ),
        ),
    ]
