# Generated by Django 4.2 on 2024-01-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_businessprocess_dgd_name_column_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="index",
            field=models.IntegerField(default=0, verbose_name="Index"),
        ),
    ]
