# Generated by Django 4.2 on 2024-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_task_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcell",
            name="value",
            field=models.TextField(blank=True, null=True, verbose_name="Value"),
        ),
    ]
