# Generated by Django 4.2 on 2024-02-01 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_alter_taskcell_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprocess",
            name="deadline",
        ),
    ]
