# Generated by Django 4.2 on 2024-02-04 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_taskstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskStatus",
        ),
    ]
