# Generated by Django 4.2 on 2024-02-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_taskstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatus",
            name="required_task_columns",
            field=models.ManyToManyField(
                blank=True,
                related_name="required_statuses",
                to="tasks.taskcolumn",
                verbose_name="Required task columns",
            ),
        ),
    ]
